language: java
before_install: mvn versions:set -DnewVersion=1.0.$TRAVIS_BUILD_NUMBER
install: mvn install -DskipTests=true --settings settings.xml

cache:
  directories:
    - ~/.m2/repository

after_success:
  - ./before-deploy.sh
  - ./deploy.sh
